- hosts: localhost
  become: true
  vars:
    users:
    - sharms
  handlers:
  - name: Update fonts
    command: fc-cache -f /usr/share/fonts
    become: true
  tasks:
  - name: Install packages
    apt: 
      name: 
      - build-essential
      - curl
      - fzf
      - git
      - jq
      - openssh-server
      - neovim
      - nvidia-cuda-toolkit
      - ripgrep
      - tmux
      - wget
      - zsh

  - name: Install miniconda
    command: ./install_miniconda.sh
  
  - name: Check if .oh-my-zsh exists
    become: yes
    become_user: '{{ item }}'
    stat:
      path: '$HOME/.oh-my-zsh'
    register: stat_oh_my_zsh_result
    tags: oh-my-zsh
    loop: '{{ users }}'

  - name: Cloning oh-my-zsh
    become: yes
    become_user: '{{ item.item }}'
    git: 
      repo: https://github.com/robbyrussell/oh-my-zsh 
      dest: '$HOME/.oh-my-zsh'
    when: not item.stat.exists
    tags: oh-my-zsh
    loop: '{{ stat_oh_my_zsh_result.results }}'

  - name: Check if zsh-syntax-highlighting
    become: yes
    become_user: '{{ item }}'
    stat:
      path: '$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'
    register: zsh_syntax_highlighting_result
    tags: oh-my-zsh
    loop: '{{ users }}'

  - name: Cloning zsh-syntax-highlighting
    become: yes
    become_user: '{{ item.item }}'
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: '$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'
    when: not item.stat.exists
    tags: oh-my-zsh
    loop: '{{ zsh_syntax_highlighting_result.results }}'

  - name: Check if zsh-autosuggestions
    become: yes
    become_user: '{{ item }}'
    stat:
      path: '$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
    register: zsh_autosuggestions_result
    tags: oh-my-zsh
    loop: '{{ users }}'

  - name: Cloning zsh-autosuggestions
    become: yes
    become_user: '{{ item.item }}'
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: '$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
    when: not item.stat.exists
    tags: oh-my-zsh
    loop: '{{ zsh_autosuggestions_result.results }}'

  - name: Check if zsh-history-substring-search
    become: yes
    become_user: '{{ item }}'
    stat:
      path: '$HOME/.oh-my-zsh/custom/plugins/zsh-history-substring-search'
    register: zsh_history_substring_search_result
    tags: oh-my-zsh
    loop: '{{ users }}'

  - name: Cloning zsh-history-substring-search
    become: yes
    become_user: '{{ item.item }}'
    git: 
      repo: https://github.com/zsh-users/zsh-history-substring-search
      dest: '$HOME/.oh-my-zsh/custom/plugins/zsh-history-substring-search'
    when: not item.stat.exists
    tags: oh-my-zsh
    loop: '{{ zsh_history_substring_search_result.results }}'
    
  - name: Set default shell for users
    become: yes
    user:
      name: '{{ item }}'
      shell: /bin/zsh
    loop: '{{ users }}'
  
  - name: Install Powerline fonts repo
    git:
      repo: https://github.com/powerline/fonts.git
      dest: /usr/src/fonts/powerline-fonts
      update: no
  
  - name: Create Powerline fonts directory
    file:
      path: /usr/share/fonts/powerline
      state: directory
  
  - name: Change install.sh to point to /usr/share/fonts/powerline
    replace:
      dest: /usr/src/fonts/powerline-fonts/install.sh
      regexp: 'font_dir="\$HOME/.local/share/fonts"'
      replace: 'font_dir="/usr/share/fonts/powerline"'
  
  - name: Copy Powerline fonts
    command: /usr/src/fonts/powerline-fonts/install.sh
    args:
      chdir: "/usr/src/fonts/powerline-fonts"
      creates: "/usr/share/fonts/powerline/Hack-Bold.ttf"
    register: PowerlineFonts_installed
    notify: Update fonts

  - name: Install Awesome Patched Fonts
    git:
      repo: https://github.com/gabrielelana/awesome-terminal-fonts
      dest: /usr/src/fonts/awesome-terminal-fonts
      update: no
  
  - name: Create Awesome fonts directory
    file:
      path: /usr/share/fonts/awesome
      state: directory
  
  - name: Copy Awesome fonts
    shell: cp -a /usr/src/fonts/awesome-terminal-fonts/build/*.ttf /usr/share/fonts/awesome
    args:
      creates: /usr/share/fonts/awesome/devicons-regular.ttf
    notify: Update fonts
  
  - name: Copy Awesome font config
    shell: cp -a /usr/src/fonts/awesome-terminal-fonts/config/10-symbols.conf /etc/fonts/conf.d
    args:
      creates: /etc/fonts/conf.d/10-symbols.conf
    notify: Update fonts

  - name: Install FiraCode Fonts
    git:
      repo: https://github.com/tonsky/FiraCode.git
      dest: /usr/src/fonts/firacode
      update: no
 
  - name: Create Firacode fonts directory
    file:
      path: /usr/share/fonts/firacode
      state: directory
  
  - name: Copy Firacode fonts
    shell: cp -a /usr/src/fonts/firacode/distr/ttf/*.ttf /usr/share/fonts/firacode
    args:
      creates: /usr/share/fonts/firacode/FiraCode-Regular.ttf
    notify: Update fonts

  - name: Apply Gnome settings
    become: yes
    become_user: '{{ item }}'
    shell: |
      gsettings set org.gnome.settings-daemon.plugins.xsettings rgba-order 'vrgb'
    loop: '{{ users }}'

  - name: add chrome apt key
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      id: 7FAC5991
      state: present
  
  - name: add chrome apt repo
    apt_repository:
      repo: deb http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: google-chrome
  
  - name: install google-chrome
    apt:
      name: google-chrome-stable
      state: present
      force: yes
      update_cache: yes
