- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: 
      name: 
      - build-essential
      - curl
      - fzf
      - git
      - neovim
      - nvidia-cuda-toolkit
      - ripgrep
      - zsh

  - name: Install miniconda
    command: ./install_miniconda.sh
  
